const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
function copy(source,target=source){const dest=path.join(out,target);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,source),dest);}
for(const name of ['style.css','app.js'])copy('website/'+name,name);
const layout=require('./layout.cjs');
for(const [key,title] of [['home','A place to call home'],['exterior','Exterior views'],['plans','Floor plan'],['interiors','Main-floor interiors'],['explore','Explore in 3D'],['budget','Budget & construction'],['library','Downloads & notes']]){
 fs.writeFileSync(path.join(out,key==='home'?'index.html':key+'.html'),layout(title,key,fs.readFileSync(path.join(__dirname,'pages',key+'.html'),'utf8')));
}
const assets=['outputs/interiors/main-living-v1.png','outputs/interiors/main-kitchen-v1.png','outputs/interiors/main-parents-v1.png','outputs/american-upper-rear.png','outputs/american-upper-rear.svg','outputs/model/house-3d.html','outputs/model/selected-a-3d-preview.png','outputs/latur-home-plan.png','outputs/latur-home-larger-rooms.png','outputs/latur-home-separate-living.png','outputs/american-family-house.png','outputs/elevations/front-option-b-warm-modern.png','outputs/elevations/front-option-c-simple-modern.png',...['front-approved.png','left-side.png','right-side.png','rear.png'].map(n=>'outputs/elevations/selected-a/'+n)];for(const file of assets)copy(file);
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function inline(s){return esc(s).replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');}
function markdown(md){const lines=md.split('\n');let result='',list=false;const endList=()=>{if(list){result+='</ul>';list=false;}};for(let i=0;i<lines.length;i++){const line=lines[i];if(line.startsWith('|')){endList();let rows=[];while(i<lines.length&&lines[i].startsWith('|'))rows.push(lines[i++]);i--;result+='<div class="table-scroll"><table>';rows.forEach((row,index)=>{if(/^\|[\s:|\-]+\|$/.test(row))return;const tag=index===0?'th':'td';result+='<tr>'+row.split('|').slice(1,-1).map(c=>`<${tag}>${inline(c.trim())}</${tag}>`).join('')+'</tr>';});result+='</table></div>';continue;}if(/^[-*] /.test(line)){if(!list){result+='<ul>';list=true;}result+='<li>'+inline(line.slice(2))+'</li>';continue;}endList();if(!line.trim())continue;const heading=line.match(/^(#{1,3}) (.+)/);result+=heading?`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`:'<p>'+inline(line)+'</p>';}endList();return result;}
for(const [slug,file,title] of [['interiors','MAIN-FLOOR-INTERIORS.md','Main-floor furniture and layout'],['budget45','BUDGET-45-LAKH.md','₹45 lakh feasibility and construction budget'],['cost','COST-ESTIMATE.md','Cost estimate'],['openings','OPENING-SCHEDULE.md','Room sizes, doors & windows'],['design','DESIGN-NOTES.md','Design notes']]){copy(file,'downloads/'+file);fs.mkdirSync(path.join(out,'documents'),{recursive:true});fs.writeFileSync(path.join(out,'documents',slug+'.html'),layout(title,slug==='cost'||slug==='budget45'?'budget':slug==='openings'?'plans':slug==='interiors'?'interiors':'library',`<article class="document"><div class="document-links"><a href="/${slug==='cost'||slug==='budget45'?'budget':slug==='openings'?'plans':slug==='interiors'?'interiors':'library'}.html">← Back to ${slug==='cost'||slug==='budget45'?'budget':slug==='openings'?'floor plan':slug==='interiors'?'interiors':'downloads'}</a><a href="/downloads/${file}" download>Download original notes ↓</a></div>${markdown(fs.readFileSync(path.join(root,file),'utf8'))}</article>`));}
copy('EXTERIOR-PRODUCT-RESEARCH.md','downloads/EXTERIOR-PRODUCT-RESEARCH.md');
fs.writeFileSync(path.join(out,'research.html'),layout('Exterior research','research',require('./research.cjs')(markdown)));
fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nDisallow: /\n');console.log('Built HM website in dist/ with selected views, plans, notes and offline 3D viewer.');
