(()=>{
const n=id=>{const el=document.getElementById(id);return el.value.trim()===''?null:Number(el.value)};
const money=v=>'₹'+v.toLocaleString('en-IN',{maximumFractionDigits:2});
const result=(el,rows,note)=>{el.querySelector('.calc-result').innerHTML=rows.map(([label,value])=>`<div><span>${label}</span><strong data-no-translate>${value}</strong></div>`).join('')+`<p>${note}</p>`;window.HMLanguage?.refresh();};
function calculate(el){let rows=[],note='';const type=el.dataset.calculator;
 if(type==='paint'){const area=n('paint-area'),coverage=n('paint-cover'),waste=n('paint-waste'),price=n('paint-price');if(area===null||coverage===null||coverage<=0||waste===null||[area,coverage,waste,price].some(v=>v!==null&&(!Number.isFinite(v)||v<0))){result(el,[],'Enter non-negative values and coverage greater than zero.');return;}const litres=area/coverage*(1+waste/100),packs=Math.ceil(litres/20);rows=[['Required litres (including allowance)',litres.toFixed(2)+' L'],['20-litre packs to buy',String(packs)],['Purchased volume',packs*20+' L'],['Topcoat material cost',price===null?'—':money(packs*price)]];note='Topcoat material only. Undercoat, preparation, labour and delivery are not included.';el.querySelector('.cost-bars').innerHTML=`<span style="width:${packs?litres/(packs*20)*100:0}%"></span>`;
 }else if(type==='roof'){const area=n('roof-area'),use=n('roof-use'),waste=n('roof-waste'),pack=n('roof-pack'),price=n('roof-price');if([area,use,waste,pack].some(v=>v===null)||use<=0||pack<=0||[area,use,waste,pack,price].some(v=>v!==null&&(!Number.isFinite(v)||v<0))){result(el,[],'Enter non-negative values, positive consumption and a pack size greater than zero.');return;}const kg=area*use*(1+waste/100),packs=Math.ceil(kg/pack);rows=[['Required material (including allowance)',kg.toFixed(2)+' kg'],['Complete packs to buy',String(packs)],['Material cost',price===null?'—':money(packs*price)]];note=price===null?'Enter a supplier price to calculate material cost. No installed total has been calculated.':'Material only. Preparation, protection, drains, labour and testing are not included.';
 }else{const w=n('opening-width'),h=n('opening-height'),c=n('opening-count'),rate=n('opening-rate'),extras=n('opening-extras');if([w,h,c,extras].some(v=>v===null)||!Number.isInteger(c)||[w,h,c,rate,extras].some(v=>v!==null&&(!Number.isFinite(v)||v<0))){result(el,[],'Enter non-negative values and a whole-number opening count.');return;}const area=w*h*c;rows=[['Total opening area',area.toFixed(2)+' sq ft'],['Quoted amount including entered extras',rate===null?'—':money(area*rate+extras)]];note=rate===null?'Enter the complete quoted assembly rate to calculate an amount.':'Confirm the quotation includes all required components, tax and installation. This is not a verified project total.';}
 result(el,rows,note);
}
document.querySelectorAll('[data-calculator]').forEach(el=>{el.addEventListener('input',()=>calculate(el));calculate(el);});
document.getElementById('paint-product')?.addEventListener('change',e=>{document.getElementById('paint-price').value=e.target.value==='custom'?'':e.target.value;calculate(e.target.closest('.calculator'));});
document.getElementById('paint-price')?.addEventListener('input',()=>{document.getElementById('paint-product').value='custom';});
document.getElementById('purchase-note')?.addEventListener('submit',e=>{e.preventDefault();const lines=['HM — '+(window.HMLanguage?.t('Exterior purchasing note')||'Exterior purchasing note'),new Date().toISOString().slice(0,10),''];for(const input of e.target.querySelectorAll('input,textarea')){const label=input.parentElement.firstChild.textContent.trim();lines.push(label+': '+(input.value||'—'),'');}const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='HM-exterior-purchasing-note.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('purchase-status').textContent=window.HMLanguage?.t('Purchasing note downloaded. Nothing was sent to a supplier.')||'Purchasing note downloaded. Nothing was sent to a supplier.';});
})();
