const fs=require('fs'),path=require('path');
const rooms=[
['living','Living room & TV','24 × 20 ft zone, including the 6 × 6 ft foyer','living',[
 ['Furniture','Retain revision 03 as option A: 7.5 × 3 ft primary sofa, 6 × 3 ft conversation sofa, 3.5 × 2 ft coffee table and 6 × 1.25 ft console. The rear sofa is conversation seating.'],
 ['Measured gaps','2 ft between table and primary sofa; 1 ft behind conversation sofa. The latter is not a passage. Approximate central eye-to-screen distance: 10 ft 4 in.'],
 ['Alternative to test','Option B: replace the conversation sofa with two movable chairs, each initially limited to 2.5 × 2.5 ft. Test them within the vacated footprint before selecting recliners or adding seats. This is a proposed alternative, not a changed model.'],
 ['Services','TV power/data behind equipment; separately switched general and evening lighting; charging beside seating without cables across circulation. Coordinate fan, curtain tracks, beams and lights before fixing ceiling points.'],
 ['Open decisions','Front direction, finished dimensions and screen outline test. Keep separate adjustable coverings for the window and patio slider. No glare-free claim is made.']]],
['kitchen','Kitchen & dining','Kitchen 20 × 14 ft · dining zone 14 × 14 ft','kitchen-dining',[
 ['Furniture','6 × 3 ft island, 2 ft-deep counters and 6 × 3 ft dining table. Six dining chairs and two island stools are drawn separately.'],
 ['Measured gaps','3.5 ft from front counter edge to island; 5.5 ft from island to right counter. These exclude drawer projections, people and appliance doors.'],
 ['Use-envelope check','For a coordination mock-up, extend each dining chair 1.5 ft outward from the table. The right end chair then reaches x=36.5 ft, leaving 1.5 ft to the pantry/service wall at x=38. This is not a comfortable through-route while occupied. Test a shorter table or revised door operation before fixing cabinetry.'],
 ['Cabinet study','Front run is 15.5 ft long and right run 8 ft long in the current model. Do not order two full runs without resolving their corner, end panels and appliances. Treat the 6 ft island as a module study; cabinet heights and worktop height must suit the users.'],
 ['Appliances','Fridge reserve is 3 × 3 ft. Request overall size, open-door dimensions, hinge clearance and ventilation for the selected model. Sink and hob shown in 3D are proposals; neither constitutes a service drawing.'],
 ['Services','Coordinate sink drain/supply and accessible shutoff; hood exhaust with an outdoor outlet and window relationship; dedicated appliance circuits as specified by the electrician; under-cabinet lighting. Island power requires a planned route before floor work.'],
 ['Release conditions','Door swings, occupied chair positions, finished sill height, corner treatment, appliance specifications and service routes must be resolved before the kitchen image or cabinetry is finalized.']]],
['parents','Parents’ bedroom & closet','Bedroom 16 × 16 ft · closet 6 × 6 ft','parents',[
 ['Furniture','Bed frame 7 × 5.5 ft, mattress assumption 6.5 × 5 ft; two 1.5 ft-square bedside tables and one 2.5 ft-square chair. Headboard stays toward the right wall.'],
 ['Measured fit','Frame reaches x=15.5 ft beside the x=16 wall line: 0.5 ft head gap, not an access route. Each bedside table has 0.5 ft nominal separation from the adjoining long bed edge in the current drawing.'],
 ['Night route','Keep the bed-to-bath route free of loose rugs, cables and projecting wardrobe doors. Verify bedroom, ensuite and closet door swings together with actual furniture.'],
 ['Closet','Current 3.5 × 1.5 ft shelving is for folded storage; it is not a complete hanging wardrobe. Study a 2 ft-deep hanging unit separately and test the door and standing space.'],
 ['Services','Provide accessible switching at entry and bedside positions; low-level night lighting as a proposal. Coordinate fan/AC with bed position, window coverings and structural beams.'],
 ['Release conditions','Actual bed/headboard dimensions, user reach preferences, clear bathroom route, window opening and closet function must be agreed.']]],
['guest','Guest bedroom','14 × 14 ft','guest',[
 ['Furniture','5.5 × 7 ft bed frame, 5 × 2 ft wardrobe and 1.5 ft-square bedside table. Preserve the current entry and both window locations.'],
 ['Measured fit','4.25 ft nominal from bed to right wall; the bedside table occupies some of this area. The wardrobe is beyond the entry at x=30.5–32.5, y=42–47.'],
 ['Wardrobe operation','Study sliding doors within the same envelope; alternatively test hinged leaf projections and standing space. Do not assume a nominal 5 ft wardrobe gives 5 ft of unobstructed internal storage.'],
 ['Services','Entry and bedside switching, charging adjacent to bed, fan centered on the usable seating/sleeping zone after beam checks; AC and drain routing are optional unfunded scope until budgeted.'],
 ['Release conditions','Door swing, wardrobe operation, curtain parking and actual mattress/frame sizes.']]],
['utility','Laundry, store, pantry & bathrooms','Laundry 6 × 8 ft · store and pantry each 6 × 6 ft','utility',[
 ['Laundry','Washer envelope: 2.5 × 2.33 ft in model coordinates; this is only a placeholder. The drawing leaves 3 ft from the left boundary to its front edge. Add manufacturer hose, door and servicing envelopes before selecting a machine.'],
 ['Store access','Keep access through laundry using the 2.5 ft nominal sliding opening at x=40.5–43, y=28. The wall to the guest bedroom remains closed. Shelf boards and stored goods must not enter the sliding-leaf travel or doorway.'],
 ['Storage','Pantry shelf: 4.5 × 1 ft. Store shelves: 3.5 × 1 ft on two adjoining sides. Specify intended goods, adjustable shelf spacing, load rating, cleanability and reachable heights with the fabricator.'],
 ['Wet services','Coordinate washer inlet/drain and utility sink with accessible traps and shutoffs. Keep electrical fittings coordinated with wet zones by the qualified designer. Confirm floor falls, waterproofing upstands and outlets without cutting structural members.'],
 ['Bathrooms','Parents’ bath 10 × 6 ft; shared bath 8 × 6 ft. Commission a fixture layout using actual WC, basin and shower dimensions, door swings and window positions. No invented approved fixture layout is added to the model.'],
 ['Release conditions','Drain route, levels, ventilation, actual fixtures, door operation and maintenance access. The existing utility/bath images remain finish studies and must be regenerated only after coordination.']]],
['upper','Upper floor & building coordination','Three rear bedrooms · front kitchen, loft and outdoor areas',null,[
 ['Retained geometry','Bedroom 3: 16 × 16 ft; bedroom 4: 14 × 16 ft; bedroom 5: 14 × 14 ft. The second kitchen is 14 × 14 ft in the current enlarged plan, not a compact kitchenette.'],
 ['Area-saving candidate','For a firm ₹45 lakh redesign, study reducing the second kitchen and loft before carrying the entire upper accommodation forward. No upper walls have been moved in this package.'],
 ['Vertical services','Overlay both floors before locating stacks. Upper rear and central bathrooms do not automatically line up with all main-floor wet rooms. Keep drainage out of open living ceilings unless a designed service route is accepted.'],
 ['Stairs and structure','The drawn 10 × 16 ft stair zone is only a reservation. Floor-to-floor height, rise/going, landings, headroom and supporting members need coordinated design before walkable stairs can be modeled.'],
 ['Exterior consistency','Prepare dimensioned elevations from the final two-floor openings schedule and compare with the selected exterior images. Rendered window proportions are not surveyed dimensions.'],
 ['Release conditions','Settled main floor, budget route, structure, stairs, outdoor drainage/railings and both-floor service routing. Upper furniture and photo production follow those decisions.']]]
];
module.exports=(root,out,layout)=>{const dir=path.join(out,'coordination');fs.mkdirSync(dir,{recursive:true});for(const [slug,title,size,crop,notes] of rooms){let body=`<article class="document"><p><a href="/coordination.html">← All coordination pages</a></p><h1>${title}</h1><p>${size}</p><p><strong>Coordination draft — current enlarged plan. Not approved for purchase or construction.</strong></p>`;if(crop)body+=`<a href="/outputs/coordination/${crop}.svg"><img src="/outputs/coordination/${crop}.svg" alt="${title}: unchanged scaled furniture and opening plan" style="display:block;width:100%;max-height:680px;object-fit:contain;background:#faf8f3"></a><p>Crop of revision 03; front toward the bottom. Furniture IDs match the full plan. Nominal room boundaries, not finished clear dimensions.</p>`;for(const [heading,text] of notes)body+=`<h2>${heading}</h2><p>${text}</p>`;body+='<p><a href="/documents/gap-audit.html">Calculated planning gaps ↗</a> · <a href="/documents/procurement.html">Contractor quote package ↗</a></p></article>';fs.writeFileSync(path.join(dir,slug+'.html'),layout(title,'interiors',body));}
const cards=rooms.map(([slug,title,size])=>`<a href="/coordination/${slug}.html"><span>ROOM COORDINATION</span><h3>${title} ↗</h3><p>${size}</p></a>`).join('');fs.writeFileSync(path.join(out,'coordination.html'),layout('Design coordination','interiors',`<section class="section"><h1>The next design work.</h1><p>Room-by-room coordination drafts tied to the saved plan. The ₹45 lakh route, site inputs and professional approvals remain open.</p><div class="download-grid">${cards}<a href="/documents/procurement.html"><span>PRICING PREPARATION</span><h3>Contractor package ↗</h3><p>Scope boundaries, quote fields and release requirements.</p></a><a href="/documents/next-steps.html"><span>HONEST STATUS</span><h3>Project checklist ↗</h3><p>Prepared work and tasks still dependent on decisions or site information.</p></a></div></section>`));};
