const pages=[['overview','Start here'],['walls','01 · Walls & paint'],['roof','02 · Roof & waterproofing'],['openings','03 · Windows, doors & railings'],['structure','04 · RCC & foundations'],['purchase','05 · Measure & purchase']];
const panel=(n,title,body)=>`<section class="guide-card"><span class="step-number">${n}</span><h2>${title}</h2>${body}</section>`;
const input=(id,label,value,step='1')=>`<label>${label}<input id="${id}" type="number" min="0" step="${step}" value="${value}" inputmode="decimal"></label>`;
const check=(text)=>`<label class="purchase-check"><input type="checkbox"> ${text}</label>`;
const layers=(items)=>`<div class="layers">${items.map((t,i)=>`<div class="layer layer-${i}"><b>${i+1}</b><span>${t}</span></div>`).join('')}</div>`;
const source=(url,label)=>`<a href="${url}" target="_blank" rel="noopener">${label} ↗</a>`;
function wrap(slug,title,body){return `<section class="section guide-page"><div class="scope-banner"><strong>EXTERIOR ONLY</strong><span>Interior purchasing and finishes will be planned separately.</span></div><span class="eyebrow">PRACTICAL CONSTRUCTION GUIDE</span><h1>${title}</h1><nav class="guide-nav" aria-label="Exterior guide navigation">${pages.map(([key,label])=>`<a href="/guides/${key}.html"${key===slug?' aria-current="page"':''}>${label}</a>`).join('')}</nav><p class="sample-note"><strong>Illustrations and calculator values are examples.</strong> They are not measured quantities or structural drawings for the current house. Enter verified project measurements and dated supplier quotes before planning a purchase.</p>${body}<div class="guide-end"><a href="/research.html">Read all manufacturer research ↗</a><a href="/documents/budget45.html">Understand the ₹45 lakh budget ↗</a><button type="button" onclick="window.print()">Print this guide</button></div></section>`;}
const content={};
content.overview=wrap('overview','Understand the outside, step by step.',`
<div class="house-map"><img src="/outputs/elevations/selected-a/front-approved.png" width="1536" height="1024" alt="Selected front elevation with numbered links to exterior components"><a style="left:18%;top:19%" href="/guides/walls.html" aria-label="1: Wall paint and cornices">1</a><a style="left:63%;top:12%" href="/guides/roof.html" aria-label="2: Roof waterproofing and parapet">2</a><a style="left:76%;top:56%" href="/guides/openings.html" aria-label="3: Windows, doors and railings">3</a><a style="left:36%;top:54%" href="/guides/structure.html" aria-label="4: Structural columns and foundations">4</a><a style="left:61%;top:81%" href="/guides/purchase.html" aria-label="5: Purchasing and site measurements">5</a></div><p class="fine">Markers identify a topic near the pictured feature. They do not locate hidden columns, footings or waterproofing layers.</p>
<div class="guide-grid">${panel('1','Walls and paint','<p>Measure the walls, choose a compatible coating system and price materials separately from preparation and labour.</p><a href="/guides/walls.html">See the wall layers & paint calculator →</a>')}${panel('2','Roof and terrace','<p>Understand the slope, waterproof membrane, protection layer, drain and parapet details.</p><a href="/guides/roof.html">See the roof layers & quantity calculator →</a>')}${panel('3','Openings and metalwork','<p>Compare complete installed window, door and railing assemblies, not a single headline rate.</p><a href="/guides/openings.html">See the measured-opening calculator →</a>')}${panel('4','RCC and foundations','<p>Understand what concrete, steel and formwork are, and which quantities must come from an engineer.</p><a href="/guides/structure.html">See the frame diagram & quote structure →</a>')}${panel('5','Purchasing','<p>Follow a numbered checklist, compare three suppliers and keep a written record before ordering.</p><a href="/guides/purchase.html">Build a printable purchasing note →</a>')}</div>`);
content.walls=wrap('walls','01 · From a bare wall to the ivory finish.',`
<div class="guide-grid">${panel('1','Understand the layers',layers(['Brick or AAC wall — chosen as a complete system','Compatible external plaster / render','Surface repairs and preparation after curing','Specified primer or waterproof basecoat','Specified exterior finish coats'])+'<p>The order is a typical explanation. Use the exact manufacturer’s approved system; putty, mesh and repair layers depend on the substrate.</p>')}${panel('2','Protect the selected appearance','<div class="finish-swatches"><span style="background:#e9dfcc">Ivory plaster</span><span style="background:#c8b69b">Small beige accent</span><span style="background:#303833;color:white">Dark metal</span><span style="background:#805a38;color:white">Warm entry finish</span></div><p>These screen colours are illustrative, not paint shade codes. Approve real samples beside the window frame and door finish.</p><p>Keep cornices modest, repeated and properly supported. Price decorative profiles separately from normal paint.</p>')}</div>
${panel('3','Calculate paint material — example only',`<div class="calculator" data-calculator="paint"><div class="calculator-inputs">${input('paint-area','Net paintable wall area (sq ft)',1000)}${input('paint-cover','Coverage for the complete coat system (sq ft / litre)',50)}${input('paint-waste','Extra allowance (%)',10)}<label>Published 20-litre price reference<select id="paint-product"><option value="8510">Apex Dust Proof · ₹8,510 / 20 L</option><option value="13840">Ultima Protek · ₹13,840 / 20 L</option><option value="custom">Use my supplier’s 20 L quote</option></select></label>${input('paint-price','Supplier price per 20 L pack (₹)',8510)}</div><div class="formula">Area ÷ complete-system coverage × (1 + extra allowance / 100)</div><div class="calc-result" aria-live="polite"></div><div class="cost-bars" aria-hidden="true"></div></div><p><strong>The default coverage of 50 sq ft/litre is a working example, not a verified coverage claim for either product.</strong> Replace it with the exact sheet’s coverage for the required coats. If a sheet gives one-coat coverage, account for the number of coats before entering it. Do not count coats twice.</p><p>Pack rounding here uses 20 L packs only. A dealer may offer a cheaper combination of smaller packs. The result covers topcoat material only: basecoat/primer, repairs, scaffolding, labour, transport and shade surcharges remain separate.</p><p>Published MRP references checked 8 September 2026: ${source('https://www.asianpaints.com/paint-products/exterior-wall-paints/apex-dustproof-emulsion.html','Apex Dust Proof')} · ${source('https://www.asianpaints.com/paint-products/exterior-wall-paints/apex-ultima-protek.html','Ultima Protek')}.</p>`)}
${panel('4','What to ask the painter',check('Measured external surface area, with opening deductions and returns')+check('Exact product, shade, sheen and compatible undercoat')+check('Coat count, specified consumption and actual number of packs')+check('Separate preparation, repair, scaffold and labour amounts')+check('Written warranty conditions and registration responsibility'))}`);
content.roof=wrap('roof','02 · Keep rain outside the house.',`
<div class="guide-grid">${panel('1','A protected terrace system',layers(['Walking finish: approved exterior tile or other protection','Compatible bedding / adhesive and protection screed','Waterproof membrane with protected upstands and details','Prepared substrate / falls as designed','Engineered RCC roof slab'])+'<p>Diagram is read from the walking surface downward. The slope layer’s position varies by specified system. The membrane must connect correctly at the drain, parapet and doorway.</p>')}${panel('2','Four details to draw first','<div class="drain-diagram"><div class="parapet">Parapet + weathered coping</div><div class="fall-arrow">Roof fall → accessible drain</div><div class="membrane">Continuous waterproofing + upstand</div><div class="slab">RCC slab</div></div><ol><li>Roof outlet and drainage fall.</li><li>Parapet coping and membrane upstand.</li><li>Door threshold and finished terrace level.</li><li>Pipe penetrations and suitable overflow provision.</li></ol><p>Drain size, slope and upstand height are not specified by this schematic.</p>')}</div>
${panel('3','Calculate membrane material — example only',`<div class="calculator" data-calculator="roof"><div class="calculator-inputs">${input('roof-area','Measured treated area, including upstands (m²)',100,.1)}${input('roof-use','Specified consumption for complete system (kg / m²)',2,.1)}${input('roof-waste','Extra allowance (%)',10)}${input('roof-pack','Pack size (kg)',35)}${input('roof-price','Supplier quote per pack (₹) — enter to price','')}</div><div class="formula">Treated area × specified consumption × (1 + extra allowance / 100)</div><div class="calc-result" aria-live="polite"></div></div><p>SikaTop-107 Seal Plus IN publishes approximately 1.5–2.0 kg/m² in two coats and 7 kg / 35 kg sets. The example uses 2.0 kg/m² and 35 kg packs; it is not a house-specific application specification. ${source('https://ind.sika.com/en/construction/waterproofing-systems/waterproofing-mortar/sikatop-107-sealplusin.html','Manufacturer system data')}.</p><p>Price is deliberately blank until you have a quote. Protection, screed, tile, details, drains, labour and tests are not included. Do not expose a system intended to be protected as a finished traffic surface.</p>`)}
${panel('4','Before covering waterproofing',check('Applicator approves substrate and compatible layer sequence')+check('Penetrations, drains and joints photographed before covering')+check('Manufacturer’s curing time completed before prescribed test')+check('Inspection / test results and installed consumption recorded')+check('Protection installed without damaging the membrane'))}`);
content.openings=wrap('openings','03 · Price complete windows, doors and railings.',`
<div class="guide-grid">${panel('1','Measure the opening','<div class="window-diagram"><span class="dimension-top">Width — example 8 ft</span><div class="window-frame"><div>Fixed / openable split to confirm</div><div>Glass specification to confirm</div></div><span>Height — example 6 ft</span></div><p>8 × 6 ft is an area example, not a glass-thickness or structural recommendation. Measure the site opening and approve a supplier shop drawing.</p>')}${panel('2','Compare the same assembly','<ol><li>Frame series, finish and opening type.</li><li>Glass build-up and safety / solar requirements.</li><li>Hardware, insect mesh and seals.</li><li>Drainage, anchors and installation.</li><li>Transport, taxes and warranty.</li></ol><p>Two “per sq ft” rates are not comparable if one excludes glass or installation.</p>')}</div>
${panel('3','Window quote calculator',`<div class="calculator" data-calculator="opening"><div class="calculator-inputs">${input('opening-width','Width (ft)',8,.1)}${input('opening-height','Height (ft)',6,.1)}${input('opening-count','Number of identical openings',1)}${input('opening-rate','Complete assembly quoted rate (₹ / sq ft)','')}${input('opening-extras','Known additional quoted costs (₹)',0)}</div><div class="formula">Width × height × count × quoted rate + known extras</div><div class="calc-result" aria-live="polite"></div></div><p>The total is only as complete as the supplier’s rate. State whether tax, fixing, mesh, glass, delivery and sealant are included. Do not add extras again if the quoted rate already covers them.</p>`)}
${panel('4','Preserve the style without guessing','<p>Use dark frames, simple vertical-bar guards and a warm entrance finish as visual targets. Request alternatives for repeated window sizes and limited fixed glass, while retaining ventilation and safe access.</p><p>Railing height, gaps, section sizes and fixings must be approved by the designer. Ask whether the rate is per running foot at a stated height, per square foot or per kilogram. Never compare unlike units.</p><p>For the main door, measure frame and shutter sizes separately and include lock, hinges, finish, threshold and weather seals. The photo does not establish an order size.</p>')}`);
content.structure=wrap('structure','04 · What supports the exterior?',`
<div class="guide-grid">${panel('1','Read the structure from top to bottom','<div class="frame-diagram"><div class="frame-slab">Roof slab</div><div class="frame-columns"><span>Column</span><span>Column</span></div><div class="frame-slab">Beam + floor slab</div><div class="frame-columns"><span>Column</span><span>Column</span></div><div class="frame-slab">Plinth beam</div><div class="footings"><span>Footing</span><span>Footing</span></div><div class="soil">Soil assessed by geotechnical investigation</div></div><p>Conceptual diagram only. It does not represent the number, position, shape or size of members in this house.</p>')}${panel('2','Three different things to price','<ol><li><strong>Concrete (m³):</strong> engineered volumes, specified mix, delivery, placement and testing.</li><li><strong>Reinforcement (kg):</strong> bar-bending schedule, approved grade, cutting, bending and fixing.</li><li><strong>Formwork (m²):</strong> measured contact area, support, erection and removal.</li></ol><p>A quoted “RCC rate” may include one, two or all three. Make the inclusions explicit.</p>')}</div>
${panel('3','Engineer-to-contractor handover','<div class="process-line"><span>Soil report</span><span>Structural drawings</span><span>Quantity bill</span><span>Comparable quotes</span><span>Approved order</span></div><p>Footing length, width, depth, column sizes, slab thickness, bar diameter and spacing remain engineer decisions. The website will not calculate safe structural sizes from a budget or photograph.</p><p>For budgeting, amount = verified quantity × quoted unit rate. Sum the defined packages once; do not duplicate foundations, plinth beams or steel in another allowance.</p>')}
${panel('4','Purchase evidence to keep',check('Engineer-approved drawing revision and material specification')+check('Concrete volume schedule and pour logistics')+check('Bar-bending schedule and steel test certificates')+check('Quotation identifies labour, pump, testing, tax and delivery')+check('Inspection before concrete placement and curing responsibility'))}`);
content.purchase=wrap('purchase','05 · From a measurement to a clear purchase order.',`
${panel('1','Use the same six steps for every product','<div class="process-line"><span>1. Locate</span><span>2. Measure</span><span>3. Specify</span><span>4. Compare</span><span>5. Approve</span><span>6. Record</span></div><p>Locate the item on the drawing. Measure the correct unit. Specify the exact product/system. Compare three complete quotes. Approve the sample and total. Record delivery and installation evidence.</p>')}
${panel('2','Know the unit before comparing prices','<div class="table-scroll"><table><tr><th>Item</th><th>Measure / buy in</th><th>Common omission</th></tr><tr><td>Paint</td><td>Surface area → litres → packs</td><td>Primer, prep and labour</td></tr><tr><td>Waterproofing</td><td>Treated m² → kg → complete kits</td><td>Upstands, drains and protection</td></tr><tr><td>Windows</td><td>Opening sq ft / complete assembly</td><td>Glass, mesh and installation</td></tr><tr><td>Cornices</td><td>Running length + profile section</td><td>Fixings, corners and scaffold</td></tr><tr><td>Railings</td><td>Length at a specified height</td><td>Coating and anchors</td></tr><tr><td>Tiles</td><td>Net area → layout waste → boxes</td><td>Adhesive, grout and edges</td></tr><tr><td>Concrete / steel / formwork</td><td>m³ / kg / m² respectively</td><td>Different rate inclusions</td></tr></table></div>')}
${panel('3','Prepare a purchasing note',`<form id="purchase-note" class="purchase-form"><label>Product / work package<input name="item" placeholder="Example: exterior paint system"></label><label>Drawing reference / location<input name="location" placeholder="Example: front and side walls"></label><label>Measured quantity and unit<input name="quantity" placeholder="Enter verified measurement"></label><label>Exact brand / model / specification<textarea name="spec" placeholder="Include colour, finish, system and accessories"></textarea></label><label>Supplier, quote date and validity<input name="supplier"></label><label>Quoted amount and included charges<textarea name="cost" placeholder="State material, labour, delivery, tax and exclusions"></textarea></label><label>Checks before ordering<textarea name="checks" placeholder="Sample approval, installer compatibility, warranty and lead time"></textarea></label><p class="fine">Your note stays in this browser session and is not sent to suppliers. Download it before leaving the page.</p><button class="button" type="submit">Download purchasing note</button><p id="purchase-status" aria-live="polite"></p></form>`)}
${panel('4','Do not place an order until these are clear',check('Quantity is measured and the unit is consistent')+check('Sample and exact specification are approved')+check('All quote inclusions, exclusions and taxes are written')+check('Price validity, delivery and unloading are confirmed')+check('Installer accepts the complete product system')+check('Invoice, batch details, warranty and installation record will be retained'))}
<p>Product references and published prices are collected in the <a href="/research.html#topic-15">research price section</a>. They are not substitutes for the written supplier quote.</p>`);
module.exports=content;
