(()=>{
const key='hm-project-workbook-v1',fields=[...document.querySelectorAll('[data-record]')];let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{};
for(const f of fields)if(typeof saved[f.dataset.record]==='string')f.value=saved[f.dataset.record];
const t=s=>window.HMLanguage?.t(s)||s;
const num=k=>{const f=fields.find(f=>f.dataset.record===k);return f.value.trim()===''?null:(f.validity.valid&&Number.isFinite(+f.value)?+f.value:NaN)};
function line(parent,label,value){const p=document.createElement('p'),s=document.createElement('span');s.textContent=label;p.append(s);if(value!==undefined){const b=document.createElement('strong');b.setAttribute('data-no-translate','');b.textContent=' '+value;p.append(b)}parent.append(p)}
function render(){const b=document.getElementById('budget-summary');b.replaceChildren();const forecasts=Array.from({length:14},(_,i)=>num('forecast-'+i)),paid=Array.from({length:14},(_,i)=>num('paid-'+i));
if([...forecasts,...paid].some(Number.isNaN)){line(b,t('Enter valid non-negative amounts.'));}else{const filled=forecasts.filter(v=>v!==null),sum=filled.reduce((a,b)=>a+b,0);line(b,t('Packages with a forecast:'),filled.length+' / 14');line(b,t('Entered forecast subtotal, lakh:'),sum.toFixed(2));line(b,t('Recorded payments, lakh:'),paid.reduce((a,b)=>a+(b||0),0).toFixed(2));if(filled.length===14)line(b,t('Budget remaining after forecast, lakh:'),(45-sum).toFixed(2));else line(b,t('Incomplete forecast: a remaining project budget cannot yet be calculated.'));if(paid.some((v,i)=>v!==null&&forecasts[i]!==null&&v>forecasts[i]))line(b,t('A payment exceeds its package forecast. Review that forecast.'));}
const q=document.getElementById('quote-summary');q.replaceChildren();const quotes=[1,2,3].map(i=>num('quote-'+i));if(quotes.some(Number.isNaN))line(q,t('Enter valid non-negative amounts.'));else if(quotes.every(v=>v!==null)){line(q,t('Lowest entered total, rupees:'),Math.min(...quotes).toLocaleString('en-IN'));line(q,t('Highest minus lowest, rupees:'),(Math.max(...quotes)-Math.min(...quotes)).toLocaleString('en-IN'));line(q,t('Compare scope and exclusions before selecting a supplier.'));}else line(q,t('Enter all three comparable totals to show the difference.'));
}
fields.forEach(f=>f.addEventListener('input',()=>{saved=Object.fromEntries(fields.map(f=>[f.dataset.record,f.value]));try{localStorage.setItem(key,JSON.stringify(saved));document.getElementById('save-status').textContent=t('Saved in this browser.');}catch{document.getElementById('save-status').textContent=t('Browser storage unavailable. Download a backup before leaving.');}render();}));
document.getElementById('project-export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({project:'HM',scope:'Compact redesign only; not approved engineering or supplier orders',exportedAt:new Date().toISOString(),units:{forecast:'INR lakh',paid:'INR lakh',quote:'INR'},records:Object.fromEntries(fields.map(f=>[f.dataset.record,f.value]))},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='HM-project-workbook.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});render();
})();
